import os

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# --- CONFIGURATION & BALANCE ---
WIDTH, HEIGHT = 960, 640
FPS = 60
BG_COLOR = (20, 20, 20)

MAX_FOOD = 110
FOOD_SPAWN_CHANCE = 0.11

INITIAL_MOTE_COUNT = 24
MOTE_MIN_SPEED = 0.5
MOTE_MIN_VISION = 20.0
MOTE_REPRODUCTION_THRESHOLD = 170.0
MOTE_POST_REPRODUCTION_ENERGY = 95.0
MOTE_SPEED_MUTATION_RANGE = (-0.5, 0.5)
MOTE_VISION_MUTATION_RANGE = (-10.0, 10.0)

PREY_THREAT_DETECTION_RADIUS = 105.0
PREY_FLEE_PRIORITY_THRESHOLD = 0.82
PREY_FLEE_BLEND_WEIGHT = 0.35
PREY_FLEE_PANIC_SPEED_MULT = 0.12
PREY_MAX_ESCAPE_SPEED_MULT = 1.15

PREY_BASE_SIZE = 1.0
PREY_MIN_SIZE = 0.75
PREY_MAX_SIZE = 1.85
PREY_SIZE_MUTATION_RATIO = 0.10
PREY_SIZE_SPEED_PENALTY = 0.55
PREY_SIZE_ENERGY_DRAIN_MULT = 0.08
PREY_RADIUS_BASE = 4
PREY_RADIUS_SCALE = 2.0

ENABLE_PREDATORS = True
INITIAL_CARNIVORE_COUNT = 2
MAX_CARNIVORES = 3

CARNIVORE_BASE_SPEED = 2.55
CARNIVORE_BASE_VISION = 145.0
CARNIVORE_BASE_SIZE = 1.35
CARNIVORE_MIN_SPEED = 1.4
CARNIVORE_MAX_SPEED = 3.25
CARNIVORE_MIN_VISION = 90.0
CARNIVORE_MAX_VISION = 210.0
CARNIVORE_MIN_SIZE = 1.05
CARNIVORE_MAX_SIZE = 2.2

CARNIVORE_START_ENERGY = 138.0
CARNIVORE_MAX_ENERGY = 320.0
CARNIVORE_REST_ENERGY_THRESHOLD = 190.0
CARNIVORE_REPRODUCTION_THRESHOLD = 250.0
CARNIVORE_POST_REPRODUCTION_ENERGY = 110.0
CARNIVORE_OFFSPRING_ENERGY = 105.0
CARNIVORE_REPRODUCTION_COOLDOWN_FRAMES = FPS * 8
CARNIVORE_ATTACK_COOLDOWN_FRAMES = max(1, FPS // 5)
CARNIVORE_DIGEST_COOLDOWN_FRAMES = int(FPS * 0.8)
CARNIVORE_MIN_ATTACK_SPEED = 0.12
CARNIVORE_MIN_ATTACK_ALIGNMENT_DOT = -0.5
CARNIVORE_ATTACK_REACH_BONUS = 3.0
CARNIVORE_REST_DRIFT_FACTOR = 0.35
CARNIVORE_REST_DRIFT_SPEED = 0.22

CARNIVORE_BASE_DRAIN = 0.065
CARNIVORE_SPEED_DRAIN_MULT = 0.048
CARNIVORE_SIZE_DRAIN_MULT = 0.078
CARNIVORE_REST_DRAIN = 0.032
CARNIVORE_SIZE_SPEED_PENALTY = 0.5

CARNIVORE_KILL_ENERGY_REWARD = 84.0
CARNIVORE_FAILED_ATTACK_PENALTY = 2.7
CARNIVORE_MIN_PREY_PER_PREDATOR = 5.0
PREDATION_SIZE_ADVANTAGE_FACTOR = 1.05

ADAPTIVE_BALANCING_ENABLED = True
ADAPTIVE_STRESS_TRIGGER = 0.68
ADAPTIVE_STRESS_RELEASE = 0.42
ADAPTIVE_PREY_FLOOR_RATIO = 0.45
ADAPTIVE_RATIO_SOFT = 0.12
ADAPTIVE_RATIO_DANGER = 0.20
ADAPTIVE_TRIGGER_FRAMES = FPS * 3
ADAPTIVE_COOLDOWN_FRAMES = FPS * 18
ADAPTIVE_MIN_ACTIVE_FRAMES = FPS * 7
ADAPTIVE_MAX_ACTIVE_FRAMES = FPS * 30
ADAPTIVE_FOOD_SPAWN_MULT = 1.45
ADAPTIVE_PREDATOR_DRAIN_BONUS = 0.015
ADAPTIVE_KILL_REWARD_MULT = 0.92
ADAPTIVE_REPRODUCTION_GATE_MULT = 1.1

CARNIVORE_SPEED_MUTATION_RANGE = (-0.25, 0.25)
CARNIVORE_VISION_MUTATION_RANGE = (-12.0, 12.0)
CARNIVORE_SIZE_MUTATION_RATIO = 0.08

CARNIVORE_RADIUS_BASE = 5
CARNIVORE_RADIUS_SCALE = 2.5

METRICS_SAMPLE_SECONDS = 0.5
METRICS_SAMPLE_FRAMES = max(1, int(FPS * METRICS_SAMPLE_SECONDS))
METRICS_OUTPUT_PATH = "metrics.csv"
METRICS_BATCH_SIZE = 30
METRICS_FLUSH_INTERVAL_SECONDS = 2.0
METRICS_QUEUE_SIZE = 256
METRICS_MAX_FILE_BYTES = 900 * 1024 * 1024
METRICS_RESET_ON_START = True

OVERLAY_BG_COLOR = (0, 0, 0, 130)
OVERLAY_TEXT_COLOR = (230, 230, 230)
OVERLAY_POS = (10, 10)
OVERLAY_BORDER_COLOR = (150, 170, 185, 120)
OVERLAY_BORDER_RADIUS = 12

GRAPH_HISTORY_POINTS = 100
GRAPH_PANEL_SIZE = (320, 150)
GRAPH_PANEL_GAP = 8
GRAPH_PANEL_BG_COLOR = (4, 12, 20, 140)
GRAPH_PANEL_BORDER_COLOR = (110, 145, 170, 130)
GRAPH_PANEL_RADIUS = 12
GRAPH_GRID_COLOR = (120, 150, 170, 45)
GRAPH_TITLE_COLOR = (220, 232, 242)
GRAPH_HINT_COLOR = (165, 185, 200)
GRAPH_POPULATION_COLOR = (105, 198, 255)
GRAPH_SPEED_COLOR = (255, 157, 114)
GRAPH_VISION_COLOR = (130, 224, 170)
GRAPH_PREDATOR_COLOR = (255, 112, 101)
GRAPH_RATIO_COLOR = (235, 207, 120)
GRAPH_STRESS_COLOR = (166, 132, 255)

MOTE_SPRITESHEET_PATH = os.path.join("resources", "coccinelle_spritesheet.png")
CARNIVORE_SPRITESHEET_PATH = os.path.join("resources", "mechant_spritesheet.png")
BACKGROUND_TEXTURE_PATH = os.path.join("resources", "grass.png")
SPRITESHEET_FRAME_WIDTH = 16
SPRITESHEET_FRAME_HEIGHT = 16
SPRITESHEET_FRAME_COUNT = 3
SPRITE_ANIMATION_FRAME_MS = 120
SPRITE_ROTATION_STEP_DEGREES = 5
MOTE_SPRITE_HEADING_OFFSET_DEGREES = -90.0
CARNIVORE_SPRITE_HEADING_OFFSET_DEGREES = -90.0
SPRITE_MOVING_SPEED_THRESHOLD = 0.05
SPRITE_RENDER_SCALE = 1
MOTE_MIN_SPRITE_SIZE_PX = 18
CARNIVORE_MIN_SPRITE_SIZE_PX = 20
