import os

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# --- CONFIGURATION & BALANCE ---
WIDTH, HEIGHT = 960, 640
FPS = 60
BG_COLOR = (20, 20, 20)

MAX_FOOD = 110
FOOD_SPAWN_CHANCE = 0.11

INITIAL_MOTE_COUNT = 24
MOTE_MIN_SPEED = 0.5
MOTE_MIN_VISION = 20.0
MOTE_REPRODUCTION_THRESHOLD = 170.0
MOTE_POST_REPRODUCTION_ENERGY = 95.0
MOTE_SPEED_MUTATION_RANGE = (-0.5, 0.5)
MOTE_VISION_MUTATION_RANGE = (-10.0, 10.0)

PREY_THREAT_DETECTION_RADIUS = 105.0
PREY_FLEE_PRIORITY_THRESHOLD = 0.82
PREY_FLEE_BLEND_WEIGHT = 0.35
PREY_FLEE_PANIC_SPEED_MULT = 0.12
PREY_MAX_ESCAPE_SPEED_MULT = 1.15

PREY_BASE_SIZE = 1.0
PREY_MIN_SIZE = 0.75
PREY_MAX_SIZE = 1.85
PREY_SIZE_MUTATION_RATIO = 0.10
PREY_SIZE_SPEED_PENALTY = 0.55
PREY_SIZE_ENERGY_DRAIN_MULT = 0.08
PREY_RADIUS_BASE = 4
PREY_RADIUS_SCALE = 2.0

ENABLE_PREDATORS = True
INITIAL_CARNIVORE_COUNT = 2
MAX_CARNIVORES = 4

CARNIVORE_BASE_SPEED = 2.5
CARNIVORE_BASE_VISION = 145.0
CARNIVORE_BASE_SIZE = 1.35
CARNIVORE_MIN_SPEED = 1.4
CARNIVORE_MAX_SPEED = 3.25
CARNIVORE_MIN_VISION = 90.0
CARNIVORE_MAX_VISION = 210.0
CARNIVORE_MIN_SIZE = 1.05
CARNIVORE_MAX_SIZE = 2.2

CARNIVORE_START_ENERGY = 138.0
CARNIVORE_MAX_ENERGY = 320.0
CARNIVORE_REST_ENERGY_THRESHOLD = 190.0
CARNIVORE_REPRODUCTION_THRESHOLD = 250.0
CARNIVORE_POST_REPRODUCTION_ENERGY = 110.0
CARNIVORE_OFFSPRING_ENERGY = 105.0
CARNIVORE_REPRODUCTION_COOLDOWN_FRAMES = FPS * 8
CARNIVORE_ATTACK_COOLDOWN_FRAMES = max(1, FPS // 5)
CARNIVORE_DIGEST_COOLDOWN_FRAMES = int(FPS * 0.8)
CARNIVORE_MIN_ATTACK_SPEED = 0.12
CARNIVORE_MIN_ATTACK_ALIGNMENT_DOT = -0.5
CARNIVORE_ATTACK_REACH_BONUS = 3.0
CARNIVORE_REST_DRIFT_FACTOR = 0.35
CARNIVORE_REST_DRIFT_SPEED = 0.22

CARNIVORE_BASE_DRAIN = 0.065
CARNIVORE_SPEED_DRAIN_MULT = 0.048
CARNIVORE_SIZE_DRAIN_MULT = 0.078
CARNIVORE_REST_DRAIN = 0.032
CARNIVORE_SIZE_SPEED_PENALTY = 0.5

CARNIVORE_KILL_ENERGY_REWARD = 84.0
CARNIVORE_FAILED_ATTACK_PENALTY = 2.7
CARNIVORE_MIN_PREY_PER_PREDATOR = 5.0
PREDATION_SIZE_ADVANTAGE_FACTOR = 1.05

ADAPTIVE_BALANCING_ENABLED = True
ADAPTIVE_STRESS_TRIGGER = 0.68
ADAPTIVE_STRESS_RELEASE = 0.42
ADAPTIVE_PREY_FLOOR_RATIO = 0.45
ADAPTIVE_RATIO_SOFT = 0.12
ADAPTIVE_RATIO_DANGER = 0.20
ADAPTIVE_TRIGGER_FRAMES = FPS * 3
ADAPTIVE_COOLDOWN_FRAMES = FPS * 18
ADAPTIVE_MIN_ACTIVE_FRAMES = FPS * 7
ADAPTIVE_MAX_ACTIVE_FRAMES = FPS * 30
ADAPTIVE_FOOD_SPAWN_MULT = 1.45
ADAPTIVE_PREDATOR_DRAIN_BONUS = 0.015
ADAPTIVE_KILL_REWARD_MULT = 0.92
ADAPTIVE_REPRODUCTION_GATE_MULT = 1.1

CARNIVORE_SPEED_MUTATION_RANGE = (-0.25, 0.25)
CARNIVORE_VISION_MUTATION_RANGE = (-12.0, 12.0)
CARNIVORE_SIZE_MUTATION_RATIO = 0.08

CARNIVORE_RADIUS_BASE = 5
CARNIVORE_RADIUS_SCALE = 2.5

METRICS_SAMPLE_SECONDS = 0.5
METRICS_SAMPLE_FRAMES = max(1, int(FPS * METRICS_SAMPLE_SECONDS))
METRICS_OUTPUT_PATH = "metrics.csv"
METRICS_BATCH_SIZE = 30
METRICS_FLUSH_INTERVAL_SECONDS = 2.0
METRICS_QUEUE_SIZE = 256
METRICS_MAX_FILE_BYTES = 900 * 1024 * 1024
METRICS_RESET_ON_START = True

OVERLAY_BG_COLOR = (0, 0, 0, 130)
OVERLAY_TEXT_COLOR = (230, 230, 230)
OVERLAY_POS = (10, 10)
OVERLAY_BORDER_COLOR = (150, 170, 185, 120)
OVERLAY_BORDER_RADIUS = 12

GRAPH_HISTORY_POINTS = 100
GRAPH_PANEL_SIZE = (320, 150)
GRAPH_PANEL_GAP = 8
GRAPH_PANEL_BG_COLOR = (4, 12, 20, 140)
GRAPH_PANEL_BORDER_COLOR = (110, 145, 170, 130)
GRAPH_PANEL_RADIUS = 12
GRAPH_GRID_COLOR = (120, 150, 170, 45)
GRAPH_TITLE_COLOR = (220, 232, 242)
GRAPH_HINT_COLOR = (165, 185, 200)
GRAPH_POPULATION_COLOR = (105, 198, 255)
GRAPH_SPEED_COLOR = (255, 157, 114)
GRAPH_VISION_COLOR = (130, 224, 170)
GRAPH_PREDATOR_COLOR = (255, 112, 101)
GRAPH_RATIO_COLOR = (235, 207, 120)
GRAPH_STRESS_COLOR = (166, 132, 255)

MOTE_SPRITESHEET_PATH = os.path.join("resources", "coccinelle_spritesheet.png")
CARNIVORE_SPRITESHEET_PATH = os.path.join("resources", "mechant_spritesheet.png")
BACKGROUND_TEXTURE_PATH = os.path.join("resources", "grass.png")
PREY_SPRITES_DIR = os.path.join("resources", "prey")
CROP_SPRITES_DIR = os.path.join("resources", "crops")
SPRITE_FILE_EXTENSIONS = (".png", ".jpg", ".jpeg", ".bmp", ".webp")
SPRITESHEET_FRAME_WIDTH = 16
SPRITESHEET_FRAME_HEIGHT = 16
SPRITESHEET_FRAME_COUNT = 3
SPRITE_ANIMATION_FRAME_MS = 120
CROP_GROWTH_FRAME_MS = 360
SPRITE_ROTATION_STEP_DEGREES = 5
MOTE_SPRITE_HEADING_OFFSET_DEGREES = -90.0
CARNIVORE_SPRITE_HEADING_OFFSET_DEGREES = -90.0
SPRITE_MOVING_SPEED_THRESHOLD = 0.05
SPRITE_RENDER_SCALE = 1
MOTE_MIN_SPRITE_SIZE_PX = 22
CARNIVORE_MIN_SPRITE_SIZE_PX = 24
FOOD_MIN_SPRITE_SIZE_PX = 16
FOOD_SPRITE_SCALE = 1.0
FOOD_COLLISION_RADIUS = 7

SEXUAL_REPRODUCTION_ENABLED = True

PREY_MATE_ENERGY_THRESHOLD = 176.0
PREY_MATE_SEARCH_RADIUS = 90.0
PREY_MATE_TOUCH_DISTANCE = 8.0
PREY_MATING_DURATION_FRAMES = int(FPS * 0.9)
PREY_REPRODUCTION_COOLDOWN_FRAMES = int(FPS * 7.0)
PREY_FAILED_MATING_COOLDOWN_FRAMES = int(FPS * 2.0)
PREY_MATE_ENERGY_COST = 38.0
PREY_MATE_CHILD_ENERGY = MOTE_POST_REPRODUCTION_ENERGY
PREY_MATING_DRAIN_MULT = 0.45

PREDATOR_MATE_ENERGY_THRESHOLD = 195.0
PREDATOR_MATE_SEARCH_RADIUS = 130.0
PREDATOR_MATE_TOUCH_DISTANCE = 11.0
PREDATOR_MATING_DURATION_FRAMES = int(FPS * 1.6)
PREDATOR_REPRODUCTION_COOLDOWN_FRAMES = int(FPS * 11.0)
PREDATOR_FAILED_MATING_COOLDOWN_FRAMES = int(FPS * 2.5)
PREDATOR_MATE_ENERGY_COST = 62.0
PREDATOR_MATE_CHILD_ENERGY = CARNIVORE_OFFSPRING_ENERGY
PREDATOR_MATING_DRAIN_MULT = 0.55

PREY_MATE_SEEK_COLOR = (102, 224, 255)
PREY_MATE_ACTIVE_COLOR = (255, 120, 196)
PREDATOR_MATE_SEEK_COLOR = (255, 208, 118)
PREDATOR_MATE_ACTIVE_COLOR = (255, 154, 104)
REPRO_RING_OFFSET = 5
REPRO_SEEK_RING_WIDTH = 1
REPRO_MATING_RING_WIDTH = 2
REPRO_MATING_PULSE_SPEED_MS = 140.0

COMMUNICATION_ENABLED = True
PHEROMONE_SEARCH_RADIUS = 115.0
PHEROMONE_CONTACT_RADIUS = 40.0
PHEROMONE_MAX_MARKERS = 120
PHEROMONE_EMIT_COOLDOWN_FRAMES = max(6, FPS // 6)
PHEROMONE_THREAT_EMIT_THRESHOLD = 0.55
PHEROMONE_SIGNAL_BLEND_WEIGHT = 0.45
PHEROMONE_FOOD_AVOID_THRESHOLD = 0.36

PHEROMONE_ALARM_INTENSITY_MULT = 0.90
PHEROMONE_RELAY_INTENSITY = 0.85
PHEROMONE_DISTRESS_INTENSITY = 1.00
PHEROMONE_KILLSITE_INTENSITY = 0.92
PHEROMONE_MATE_INTENSITY_PREY = 0.74
PHEROMONE_MATE_INTENSITY_PREDATOR = 0.94

PHEROMONE_ALARM_MAX_AGE_FRAMES = int(FPS * 2.0)
PHEROMONE_RELAY_MAX_AGE_FRAMES = int(FPS * 0.7)
PHEROMONE_DISTRESS_MAX_AGE_FRAMES = int(FPS * 1.3)
PHEROMONE_KILLSITE_MAX_AGE_FRAMES = int(FPS * 1.8)
PHEROMONE_MATE_MAX_AGE_FRAMES = int(FPS * 7.2)
PHEROMONE_MATE_EMIT_COOLDOWN_FRAMES = max(8, FPS // 5)
PHEROMONE_MATE_SEARCH_RADIUS_PREY = 155.0
PHEROMONE_MATE_SEARCH_RADIUS_PREDATOR = 255.0
PHEROMONE_MATE_BLEND_WEIGHT = 0.72
PREDATOR_MATE_PHEROMONE_LOCK_THRESHOLD = 0.16
PREDATOR_MATE_PHEROMONE_TURN_MIN = 0.24
PREDATOR_MATE_PHEROMONE_TURN_MAX = 0.60

SAFENESS_GROUPING_ENABLED = True
SAFENESS_BASELINE = 0.30
SAFENESS_ALLY_RADIUS = 80.0
SAFENESS_ANCHOR_RADIUS = 130.0
SAFENESS_NEARBY_ALLY_SCALE = 0.16
SAFENESS_THREAT_WEIGHT = 0.62
SAFENESS_PHEROMONE_WEIGHT = 0.38
SAFENESS_JOIN_THRESHOLD = 0.52
SAFENESS_LEAVE_THRESHOLD = 0.40
SAFENESS_GROUP_INFLUENCE_MIN = 0.08
SAFENESS_GROUP_INFLUENCE_MAX = 0.32
SAFENESS_COHESION_WEIGHT = 0.62
SAFENESS_ALIGNMENT_WEIGHT = 0.24
SAFENESS_SEPARATION_WEIGHT = 0.30
SAFENESS_SEPARATION_RADIUS = 24.0

CAMERA_DIRECTOR_ENABLED = True
CAMERA_MAP_FOCUS_WEIGHT = 0.72
CAMERA_PREY_SUBJECT_WEIGHT = 0.70
CAMERA_SUBJECT_MIN_AGE_FRAMES = int(FPS * 8.0)
CAMERA_MAP_SHOT_MIN_FRAMES = int(FPS * 24.0)
CAMERA_MAP_SHOT_MAX_FRAMES = int(FPS * 42.0)
CAMERA_SUBJECT_SHOT_MIN_FRAMES = int(FPS * 18.0)
CAMERA_SUBJECT_SHOT_MAX_FRAMES = int(FPS * 32.0)
CAMERA_MAP_ZOOM = 1.0
CAMERA_PREY_ZOOM = 1.45
CAMERA_PREDATOR_ZOOM = 1.30
CAMERA_MIN_ZOOM = 1.0
CAMERA_MAX_ZOOM = 1.80
CAMERA_FOLLOW_LERP = 0.06
CAMERA_ZOOM_LERP = 0.045
CAMERA_USE_SMOOTHSCALE = True

PHEROMONE_DEBUG_DRAW_DEFAULT = False
PHEROMONE_DEBUG_ALPHA = 80
PHEROMONE_DEBUG_RADIUS_MIN = 6
PHEROMONE_DEBUG_RADIUS_SCALE = 18
